name: cicd_test_deploy

on: [push]

jobs:
  tests:
    name: Pytest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        run: pytest
