name: cicd_test_deploy

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        run: pytest
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: milssky/cicd_test
          tag_with_ref: true