name: cicd_test_deploy

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        run: pytest
